name: Tests

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 6 (LTS)
          - laravel: 6.*
            php: 7.2
          - laravel: 6.*
            php: 7.3
          - laravel: 6.*
            php: 7.4
          - laravel: 6.*
            php: 8.0

          # Laravel 7
          - laravel: 7.*
            php: 7.2
          - laravel: 7.*
            php: 7.3
          - laravel: 7.*
            php: 7.4
          - laravel: 7.*
            php: 8.0

          # Laravel 8 (LTS)
          - laravel: 8.*
            php: 7.3
          - laravel: 8.*
            php: 7.4
          - laravel: 8.*
            php: 8.0
          - laravel: 8.*
            php: 8.1

          # Laravel 9 (LTS)
          - laravel: 9.*
            php: 8.0
          - laravel: 9.*
            php: 8.1
          - laravel: 9.*
            php: 8.2

          # Laravel 10
          - laravel: 10.*
            php: 8.1
          - laravel: 10.*
            php: 8.2
          - laravel: 10.*
            php: 8.3

          # Laravel 11
          - laravel: 11.*
            php: 8.2
          - laravel: 11.*
            php: 8.3
          - laravel: 11.*
            php: 8.4

    name: L${{ matrix.laravel }} - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
          coverage: none

      # -------------------------------------------------------------
      # TEST 1: PREFER LOWEST (Checks minimum version compatibility)
      # -------------------------------------------------------------
      - name: Install Dependencies (Lowest)
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-lowest --prefer-dist --no-interaction

      - name: Execute Tests (Lowest)
        run: vendor/bin/phpunit

      # -------------------------------------------------------------
      # TEST 2: PREFER STABLE (Checks current version compatibility)
      # -------------------------------------------------------------
      - name: Install Dependencies (Stable)
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute Tests (Stable)
        run: vendor/bin/phpunit